### PR TITLE
Implement a runtime-creation-sized Bloom Filter

### LINKED ISSUE #4: Support runtime / dynamic bloom sizing
# Summary

## Problem

Bloom Filter sizes are currently pre-defined - for CAR mirror (e.g.) we'll want to be able to dynamically pick a size. 

### Impact

Limited sizes - determined at compile time - for all bloom filters created by this library.

## Solution

Allow for dynamic bloom filter sizing. (As @matheus23 pointed out: https://github.com/wnfs-wg/deterministic-bloom/pull/2#issuecomment-1443465381 )

### PR DESCRIPTION
**Pull request by matheus23**
# Description

- Adds a bloom filter implementation `runtime_sized::BloomFilter`
- Splits out bloom filter implementations across modules
- Implements rejection sampling in `HashIndexIterator` (has no effect if the size is a power of two)

## Link to issue

Fixes #4 

## Type of change

- [x] New feature (non-breaking change that adds functionality)
- [x] Refactor (non-breaking change that updates existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Comments have been added/updated

## Test plan (required)

- [x] ~~Needs more tests. Consider this somewhat WIP.~~

### CODE REVIEW

**Comment by matheus23** [comment]
Argh, why does the benchmark bot have to ping Brooke? :sweat_smile:

**Comment by matheus23** [comment]
I looked a bit into what's happening with performance, and honestly I just think it's some kind of optimization not kicking in in one case vs. another.

Here's a call graph cpu cycle graph from the state in this PR:
image

vs. the state before the PR:
image


As you can see it's basically doing the same thing except in one case, to set bits in the bitvec it uses `deref_mut` whereas in the other case it's using `set`.
For some reason the version with `set` is much faster than the version using `deref_mut`. Keep in mind in both cases this is using exactly the same code to set bits (the `BitSlice::set` method).

The thing that I mainly wanted to make sure was not the culprit are the changes in the `HashIndexIterator::next` function, but as you can see apparently that's using less time in the new version version before, so :man_shrugging:

**Review by appcypher — APPROVED** [review]
This generally looks good to me. 
Not a major issue but would `Box<[u8]>` better be represented as `Bytes` here?

**Comment by matheus23** [comment]
@appcypher Yeah, valid question. Generally I didn't need any functionality from `Bytes` (e.g. don't need the sharing/refcounting), so I went with the most "barebones" way that works.
I actually kinda wanted to make `BloomFilter { k_hashes: u32, bytes: [u8] }` work, but it's difficult working with unsized types (e.g. missing a `Clone` implementation).

**Pull request merged**
